### ISSUE TITLE
Emmet expansion doesn't work

### ISSUE THREAD

**Issue by enzy** [kasik96/VS-Latte#4]
Current behavior:
- `p` + Tab results in `p `
- `.someClass` + Tab results in `.someClass`

Expected behavior:
- `p` + Tab results in `<p></p>`
- `.someClass` + Tab results in `<div class="someClass"></div>`

**Comment by kasik96** [comment]
Currently there is no support for Emmet.

**Comment by enzy** [comment]
It's all about the correct scoping, isn't it?

**Comment by MartinKokesCz** [comment]
Just add this to settings.json

    "emmet.includeLanguages": {
        "latte": "html"
    }
